# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mate/ui/ui_dlgNuevoProducto.ui'
#
# Created: Sat Mar 28 03:10:48 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlgNuevoProducto(object):
    def setupUi(self, dlgNuevoProducto):
        dlgNuevoProducto.setObjectName(_fromUtf8("dlgNuevoProducto"))
        dlgNuevoProducto.resize(444, 322)
        self.verticalLayout = QtGui.QVBoxLayout(dlgNuevoProducto)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblCod = QtGui.QLabel(dlgNuevoProducto)
        self.lblCod.setObjectName(_fromUtf8("lblCod"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblCod)
        self.lineCod = QtGui.QLineEdit(dlgNuevoProducto)
        self.lineCod.setObjectName(_fromUtf8("lineCod"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineCod)
        self.lblNombre = QtGui.QLabel(dlgNuevoProducto)
        self.lblNombre.setObjectName(_fromUtf8("lblNombre"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblNombre)
        self.lineNombre = QtGui.QLineEdit(dlgNuevoProducto)
        self.lineNombre.setObjectName(_fromUtf8("lineNombre"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineNombre)
        self.lblCodExt = QtGui.QLabel(dlgNuevoProducto)
        self.lblCodExt.setObjectName(_fromUtf8("lblCodExt"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblCodExt)
        self.lineCodExt = QtGui.QLineEdit(dlgNuevoProducto)
        self.lineCodExt.setObjectName(_fromUtf8("lineCodExt"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineCodExt)
        self.lblPrecioCompra = QtGui.QLabel(dlgNuevoProducto)
        self.lblPrecioCompra.setObjectName(_fromUtf8("lblPrecioCompra"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblPrecioCompra)
        self.lblPrecio = QtGui.QLabel(dlgNuevoProducto)
        self.lblPrecio.setObjectName(_fromUtf8("lblPrecio"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblPrecio)
        self.lblStock = QtGui.QLabel(dlgNuevoProducto)
        self.lblStock.setObjectName(_fromUtf8("lblStock"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblStock)
        self.lblStockMin = QtGui.QLabel(dlgNuevoProducto)
        self.lblStockMin.setObjectName(_fromUtf8("lblStockMin"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblStockMin)
        self.lblStockIdeal = QtGui.QLabel(dlgNuevoProducto)
        self.lblStockIdeal.setObjectName(_fromUtf8("lblStockIdeal"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblStockIdeal)
        self.lblRubro = QtGui.QLabel(dlgNuevoProducto)
        self.lblRubro.setObjectName(_fromUtf8("lblRubro"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lblRubro)
        self.comboRubro = QtGui.QComboBox(dlgNuevoProducto)
        self.comboRubro.setObjectName(_fromUtf8("comboRubro"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.comboRubro)
        self.lblDesc = QtGui.QLabel(dlgNuevoProducto)
        self.lblDesc.setObjectName(_fromUtf8("lblDesc"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.lblDesc)
        self.lineDesc = QtGui.QLineEdit(dlgNuevoProducto)
        self.lineDesc.setObjectName(_fromUtf8("lineDesc"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineDesc)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dSpinBoxPrecioCompra = QtGui.QDoubleSpinBox(dlgNuevoProducto)
        self.dSpinBoxPrecioCompra.setDecimals(3)
        self.dSpinBoxPrecioCompra.setMaximum(9999.99)
        self.dSpinBoxPrecioCompra.setObjectName(_fromUtf8("dSpinBoxPrecioCompra"))
        self.horizontalLayout.addWidget(self.dSpinBoxPrecioCompra)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dSpinBoxPrecio = QtGui.QDoubleSpinBox(dlgNuevoProducto)
        self.dSpinBoxPrecio.setMaximum(9999.99)
        self.dSpinBoxPrecio.setObjectName(_fromUtf8("dSpinBoxPrecio"))
        self.horizontalLayout_2.addWidget(self.dSpinBoxPrecio)
        self.spinRatio = QtGui.QDoubleSpinBox(dlgNuevoProducto)
        self.spinRatio.setMaximum(9999.99)
        self.spinRatio.setObjectName(_fromUtf8("spinRatio"))
        self.horizontalLayout_2.addWidget(self.spinRatio)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.spinStock = QtGui.QSpinBox(dlgNuevoProducto)
        self.spinStock.setObjectName(_fromUtf8("spinStock"))
        self.horizontalLayout_3.addWidget(self.spinStock)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spinStockIdeal = QtGui.QSpinBox(dlgNuevoProducto)
        self.spinStockIdeal.setMinimum(1)
        self.spinStockIdeal.setMaximum(999)
        self.spinStockIdeal.setObjectName(_fromUtf8("spinStockIdeal"))
        self.horizontalLayout_5.addWidget(self.spinStockIdeal)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.spinStockMin = QtGui.QSpinBox(dlgNuevoProducto)
        self.spinStockMin.setMinimum(1)
        self.spinStockMin.setMaximum(999)
        self.spinStockMin.setObjectName(_fromUtf8("spinStockMin"))
        self.horizontalLayout_4.addWidget(self.spinStockMin)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(dlgNuevoProducto)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtGui.QDialogButtonBox(dlgNuevoProducto)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblCod.setBuddy(self.lineCod)
        self.lblNombre.setBuddy(self.lineNombre)
        self.lblCodExt.setBuddy(self.lineCodExt)
        self.lblPrecioCompra.setBuddy(self.dSpinBoxPrecioCompra)
        self.lblPrecio.setBuddy(self.dSpinBoxPrecio)
        self.lblStock.setBuddy(self.spinStock)
        self.lblStockMin.setBuddy(self.spinStockMin)
        self.lblStockIdeal.setBuddy(self.spinStockIdeal)
        self.lblRubro.setBuddy(self.comboRubro)
        self.lblDesc.setBuddy(self.lineDesc)

        self.retranslateUi(dlgNuevoProducto)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dlgNuevoProducto.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dlgNuevoProducto.reject)
        QtCore.QObject.connect(self.lineCod, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.lineNombre.setFocus)
        QtCore.QObject.connect(self.lineNombre, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.lineCodExt.selectAll)
        QtCore.QObject.connect(self.lineCod, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.lineNombre.selectAll)
        QtCore.QObject.connect(self.lineNombre, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.lineCodExt.setFocus)
        QtCore.QObject.connect(self.lineCodExt, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.dSpinBoxPrecioCompra.selectAll)
        QtCore.QObject.connect(self.lineCodExt, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.dSpinBoxPrecioCompra.setFocus)
        QtCore.QMetaObject.connectSlotsByName(dlgNuevoProducto)
        dlgNuevoProducto.setTabOrder(self.lineCod, self.lineNombre)
        dlgNuevoProducto.setTabOrder(self.lineNombre, self.lineCodExt)
        dlgNuevoProducto.setTabOrder(self.lineCodExt, self.dSpinBoxPrecioCompra)
        dlgNuevoProducto.setTabOrder(self.dSpinBoxPrecioCompra, self.dSpinBoxPrecio)
        dlgNuevoProducto.setTabOrder(self.dSpinBoxPrecio, self.spinRatio)
        dlgNuevoProducto.setTabOrder(self.spinRatio, self.spinStock)
        dlgNuevoProducto.setTabOrder(self.spinStock, self.spinStockMin)
        dlgNuevoProducto.setTabOrder(self.spinStockMin, self.spinStockIdeal)
        dlgNuevoProducto.setTabOrder(self.spinStockIdeal, self.comboRubro)
        dlgNuevoProducto.setTabOrder(self.comboRubro, self.lineDesc)
        dlgNuevoProducto.setTabOrder(self.lineDesc, self.buttonBox)

    def retranslateUi(self, dlgNuevoProducto):
        dlgNuevoProducto.setWindowTitle(_translate("dlgNuevoProducto", "Nuevo Producto", None))
        self.lblCod.setText(_translate("dlgNuevoProducto", "&Código:", None))
        self.lblNombre.setText(_translate("dlgNuevoProducto", "&Nombre", None))
        self.lblCodExt.setText(_translate("dlgNuevoProducto", "C&od. Externo:", None))
        self.lblPrecioCompra.setText(_translate("dlgNuevoProducto", "&Precio: compra", None))
        self.lblPrecio.setText(_translate("dlgNuevoProducto", "P&recio:", None))
        self.lblStock.setText(_translate("dlgNuevoProducto", "&Stock", None))
        self.lblStockMin.setText(_translate("dlgNuevoProducto", "Stoc& mímimo:", None))
        self.lblStockIdeal.setText(_translate("dlgNuevoProducto", "Stock &ideal:", None))
        self.lblRubro.setText(_translate("dlgNuevoProducto", "&R&ubro:", None))
        self.lblDesc.setText(_translate("dlgNuevoProducto", "&Descripción:", None))
        self.dSpinBoxPrecioCompra.setPrefix(_translate("dlgNuevoProducto", "$ ", None))
        self.dSpinBoxPrecio.setPrefix(_translate("dlgNuevoProducto", "$ ", None))
        self.spinRatio.setSuffix(_translate("dlgNuevoProducto", " %", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    dlgNuevoProducto = QtGui.QDialog()
    ui = Ui_dlgNuevoProducto()
    ui.setupUi(dlgNuevoProducto)
    dlgNuevoProducto.show()
    sys.exit(app.exec_())

